# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macos-latest

steps:

- script: |
    cd iGoat-Swift
    xcodebuild -list 
    xcodebuild -showsdks
    ls -la **/**
    xcodebuild -project iGoat-Swift.xcodeproj -list
    pod install
    xcodebuild archive -workspace iGoat-Swift.xcworkspace -configuration Debug -scheme iGoat-Swift -destination generic/platform=iOS DEBUG_INFORMATION_FORMAT=dwarf-with-dsym -archivePath iGoat-Swift.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO | tee build_log.txt
    ls -la
    brew tap veracode/tap
    brew install gen-ir
    gen-ir build_log.txt iGoat-Swift.xcarchive --project-path iGoat-Swift.xcodeproj
    ls -la iGoat-Swift.xcarchive
    zip -r iGoat-Swift.zip iGoat-Swift.xcarchive
    pwd
    ls -la
  displayName: 'Check SDKs and list out the project and files'  
  
- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Service Connection'
    AnalysisService: 'Veracode_Int'
    veracodeAppProfile: 'iGoat-Swift'
    version: '$(build.buildNumber)'
    filepath: '/Users/runner/work/1/s/iGoat-Swift.zip'
    sandboxName: 'ADO'
    createSandBox: true
    createProfile: true
    importResults: true
    maximumWaitTime: '360'

