name: Xcode - Build and Analyze

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Gen-IR
        run: |
          brew tap veracode/tap
          brew install gen-ir
      - name: Build
        run: |
          cd iGoat-Swift
          xcodebuild archive -workspace iGoat-Swift.xcworkspace -sdk iphoneos16.2 -configuration Debug -scheme iGoat-Swift -destination generic/platform=iOS DEBUG_INFORMATION_FORMAT=dwarf-with-dsym -archivePath iGoat-Swift.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO | tee build_log.txt
          gen-ir build_log.txt iGoat-Swift.xcarchive --project-path iGoat-Swift.xcodeproj
        #  xcodebuild archive -scheme iGoat-Swift -project iGoat-Swift.xcodeproj -archivePath iGoat-Swift.xcarchive -configuration Debug DEBUG_INFORMATION_FORMAT=dwarf-with-dsym CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO >> build_log.txt
          
        #  ls -la iGoat-Swift.xcarchive/*
        #  zip -r iGoat-Swift.zip iGoat-Swift.xcarchive
        #xcodebuild archive -scheme iGoat-Swift -workspace iGoat-Swift.xcworkspace -archivePath iGoat-Swift.xcarchive -configuration Debug DEBUG_INFORMATION_FORMAT=dwarf-with-dsym CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO ENABLE_BITCODE=NO >> build_log.txt

          
